services:
  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: on-failure
    secrets:
      - mariadb_root_password
      - mariadb_password

  wordpress:
    image: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: on-failure
    secrets:
      - wp_admin_password
      - wp_user_password
      - mariadb_password

  nginx:
    image: nginx
    build:
      context: ./requirements/nginx
      args:
        DOMAIN_NAME: belinore.42.fr
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html:ro
    networks:
      - inception
    restart: on-failure
    secrets:
      - ssl_certificate
      - tls_private_key

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      # Final 42 VM path:
      # device: /home/belinore/data/mariadb
      device: /Users/beth/in_progress/inception/data/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      # Final 42 VM path:
      # device: /home/belinore/data/wordpress
      device: /Users/beth/in_progress/inception/data/wordpress

networks:
  inception:
    driver: bridge

secrets:
  mariadb_root_password:
    file: ../secrets/MARIADB_ROOT_PASSWORD
  mariadb_password:
    file: ../secrets/MARIADB_PASSWORD
  wp_admin_password:
    file: ../secrets/WP_ADMIN_PASSWORD
  wp_user_password:
    file: ../secrets/WP_USER_PASSWORD
  ssl_certificate:
    file: ../secrets/SSL_CERTIFICATE
  tls_private_key:
    file: ../secrets/TLS_PRIVATE_KEY
